version: '3.8'
# definir container
services:

  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
  # spring app
  operateur:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  db_data:
networks:
  mynetwork:
